### ISSUE TITLE
As a user, upon opening the web service I want it to remember I gave permission to use my microphone, so that I don't have to give it permission every time.

### ISSUE THREAD

**Issue by electron1029** [Code-Purple/peon#16]

**Comment by ashleybarton** [comment]
I'm trying to find the article, but I recall reading that as long as we have the website in http, it will ask the user if he/she would like to set the microphone permission every time. If https, it will ask once and remember that permission. This has become somewhat of a privacy issue since the web service could theoretically start listening at any point in time without asking the user their permission.
