### ISSUE TITLE
Implement an example from the Web Speech API in Javascript

### ISSUE THREAD

**Issue by electron1029** [Code-Purple/peon#2]
https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#examples

**Comment by mmlevy** [comment]
Unfortunately, these examples don't make sense to me. For instance, in the first example, there is a reference to a variable "q" and I have no idea what type it is or even what it is because the example doesn't show it being initialized. And what do you mean by "implement an example"? Aren't these examples implemented in javascript already? Or do you mean for me to come up with my own example? So far, I don't even know enough javascript to understand these examples and I'm not sure which parts are part of the speech api. Hopefully we can meet on monday to discuss this.

**Comment by electron1029** [comment]
By implement I mean put it on our project. Let me look at the example and see if I can explain it to you.

**Comment by electron1029** [comment]
I committed an example to the project. You can test it out at localhost:8080/test.html. There are some javascript files that go with it.
Let me know if it helps you at all.

**Comment by mmlevy** [comment]
It looks like I'm getting a strange error with spring when I try and run it. Well, a huge list of errors actually. I actually tested the original demo web application too with the same errors so something is wrong with my eclipse build apparently. It used to work though. I will bring my mac to class on monday so maybe you can help me figure out what's going on.

**Comment by electron1029** [comment]
Yeah I'm not sure. It works for me but I'm running Windows. If it doesn't work for someone else let me know.
@mmlevy Just to clarify, before you ran the project did you right click on it, select Maven, and select Update Maven project to load the new jars?

**Comment by mmlevy** [comment]
Alright, well for some odd reason, restarting my computer fixed it. Very odd. Anyways, the example doesn't do anything (unless my mic isn't working?). Also yes I did all of that update stuff correctly which is why I was puzzled about it not working. Somewhere is said something about that address already being in use. I'm guessing restarting my computer somehow freed it up. I wish I knew what happened honestly. Where is this javascript file in this example? I look in WebController.java and I see nothing new. Yet I use the url you said and it shows me the example that you mentioned, although it doesn't actually do anything. What is it supposed to do?

**Comment by mmlevy** [comment]
I see a lot of new files actually that you added and I definitely don't understand what you did. Please meet after class on monday. I desperately need help because I am very lost unfortunately.

**Comment by electron1029** [comment]
Click on the mic in the corner of the box and it'll ask you to use the mic and you can talk and it'll put what you say in the box. I tested it on Chrome.

**Comment by mmlevy** [comment]
Tested on both firefox and safari. Clicking the mic does nothing. I believe you when you say it works, I'm sorry that I can't test it though. Are you able to stay on Monday? I have a lot of questions about pretty much everything.

**Comment by electron1029** [comment]
yes, I will be there!
